name: chatgse
channels:
  - conda-forge
dependencies:
  - python=3.10
  - openai=0.27.4
  - streamlit=1.21.0
  - pandas=1.3.*
  - tabulate=0.9.*
  - loguru=0.7.*
  - langchain=0.0.*
  - retry=0.9.*
  - nltk=3.8.*